### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by cpgruber** [cpgruber/atlas-shared#11]
Mind if I transfer ownership of this repo to one of y'all? @zacharykolsky @tylercrosse

**Comment by tylercrosse** [comment]
Yeah no problem, I don't mind taking it

**Comment by zacharykolsky** [comment]
Sure.  What do I need to do?

Thanks very much,

Zak

Zachary Kolsky
zacharykolsky@gmail.com
202-486-9414

**Comment by zacharykolsky** [comment]
How was the first week?

Zachary Kolsky
zacharykolsky@gmail.com
202-486-9414

**Comment by cpgruber** [comment]
Ok I'm gonna give it to zak since he's in charge. Remember to change your remote url. @Solowt not sure how this will affect your fork

**Comment by cpgruber** [comment]
@zacharykolsky I initiated a transfer to you yesterday, I think all you need to do is accept it.

**Comment by zacharykolsky** [comment]
Hey - 

Sorry, that link expired.  Can you resend?

Thanks,

Zak

**Comment by cpgruber** [comment]
@zacharykolsky just reinstated the transfer, let me know if you get it.
